name: Build and Unit Test

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Initialize and Build
      run: |
        pwd
        ls
        ls ${{ github.workspace }}
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=RelWithDebugInfo -DENABLE_TESTING=ON
        make
    - name: Run Unit Tests
      working-directory: build
      run: |
        make run_tests
