name: Lint

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Utils
      uses: actions/checkout@v2
      with:
        path: utils
        submodules: recursive
    - name: Run clang-format
      working-directory: utils
      run: |
        sudo apt install clang-format-14
        which clang-format-14
        clang-format-14 --version
        alias clang-format="clang-format-14"
        sh validate-format.sh $(find . -name "*.c" -type f -print)
        sh validate-format.sh $(find . -name "*.cc" -type f -print)
