name: Build and Unit Test

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Check out Utils
      uses: actions/checkout@v2
      with:
        path: utils
        submodules: recursive
    - name: Initialize and Build
      working-directory: utils
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=RelWithDebugInfo -DENABLE_TESTING=ON
        make
    - name: Run Unit Tests
      working-directory: utils/build
      run: |
        make run_tests
