name: Lint

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Utils
      uses: actions/checkout@v2
      with:
        path: utils
        submodules: recursive
    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        exclude: './lib'
        extensions: 'h,cc'
        clangFormatVersion: 14
