name: Build and Unit Test

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.22.1'
    - name: Cache libcheck
      id: cache-libcheck
      uses: actions/cache@v2
      env:
        cache-name: libcheck
      with:
        path: check-0.15.2
        key: check-0.15.2-${{ runner.os }}-v2
    - name: Download libcheck
      uses: actions/checkout@v2
      if: steps.cache-libcheck.outputs.cache-hit != 'true'
      with:
        repository: "libcheck/check"
        ref: "0.15.2"
        path: check-0.15.2
    - name: Build libcheck
      id: build-libcheck
      if: steps.cache-libcheck.outputs.cache-hit != 'true'
      working-directory: check-0.15.2
      run: |
        mkdir build && cd build
        cmake ..
        make
    - name: install libcheck
      working-directory: check-0.15.2/build
      run: |
        sudo make install
    - name: install ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libsubunit-dev lsb-release
        echo $LD_LIBRARY_PATH
        echo "2"
        ls /usr/local/lib
    - name: Check out Utils
      uses: actions/checkout@v2
      with:
        path: utils
        submodules: recursive
    - name: Initialize and Build
      working-directory: utils
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=RelWithDebugInfo -DENABLE_TESTING=ON -DBUILD_SHARED_LIBRARY=OFF
        make
        objdump -D libutils.a --demangle --syms
    - name: Run Unit Tests
      working-directory: utils/build
      run: |
        lldb test/utils_unit_testing -o run
        make run_tests
