name: Lint

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Utils
      uses: actions/checkout@v2
      with:
        path: utils
        submodules: recursive
    - name: Run clang-format 2
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        exclude: './lib'
        extensions: 'h,cc'
        clangFormatVersion: 14
    - name: Run clang-format
      working-directory: utils
      run: |
        sudo apt-get install clang-format
        which clang-format
        clang-format --version
        sh validate-format.sh $(find . -name "*.c" -type f -print)
        sh validate-format.sh $(find . -name "*.cc" -type f -print)
